### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by cludden** [cludden/protoc-gen-go-temporal#6]
(potentially breaking) ideas in preparation of a future v1 release:

## Accepted
- [x] add support for experimental updates
- [x] make options optional to avoid passing nils for default behavior
- [x] move default options to parent message
- [x] restrict rpc method option combinations to `activity`, `activity+workflow`, `query`, `signal`, `update`
- [ ] add NewTestClient method that accepts testsuite.WorkflowTestEnv
- [x] add support for default search attributes mapping
- [ ] add support for documentation generation
- [ ] convert optional options to functional options to support further extension
- [x] for all operations that support asynchronous invocation, add sync and async implementations for each (e.g. `SomeWorkflow(context.Context, *SomeWorkflowRequest, ...StartWorkflowOption) (*SomeWorkflowResponse, error)` and `SomeWorkflowAsync(context.Context, *SomeWorkflowRequest, ...StartWorkflowOption) (SomeWorkflowRun, error)`

## Proposed
- [ ] support multiple proto services in a single package
- [ ] make `query`, `signal`, `update` methods available only from lazily initialized `get` method
- [ ] add multiple flavors of local activity methods (by func, by name)

**Comment by cludden** [comment]
See #7
